version: 0.0
os: linux

files:
  - source: /target/dhaneeshdharun.war
    destination: /opt/tomcat/webapps/
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stopserver.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/startserver.sh
      timeout: 300
      runas: root
 
