version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing Java Corretto 11"
  pre_build:
    commands:
      - echo "installing the dependencies from the maven main stream and store it in codeartifact repo and use it for code build"
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain dhaneesh-domain --domain-owner 494713367427 --region ap-northeast-1 --query authorizationToken --output text`

  build:
    commands:
      - echo "codebuild starts"  
      - mvn -s settings.xml clean
      - echo "compileing the code" 
      - mvn -s settings.xml compile
  post_build:
    commands:
      - echo "packaging the code and no errors"
      - mvn -s settings.xml package
artifacts:
  files:
      - target/dhaneeshdharun.war
      - appspec.yaml
      - scripts/*
  discard-paths: no